### ISSUE TITLE
畅想一下以后可以把这个提交到idf 上游去

### ISSUE THREAD

**Issue by supperthomas** [RT-Thread-packages/esp-idf#3]
### Is your feature request related to a problem?

nop

### Describe the solution you'd like.

upstream

### Describe alternatives you've considered.

pull request upstream

### Additional context.

加油。~

**Comment by mysterywolf** [comment]
涛哥目前使用这个软件包的时候一定要用github镜像源 因为这里边还有submodule的问题没有解决

**Comment by supperthomas** [comment]
> 涛哥目前使用这个软件包的时候一定要用github镜像源 因为这里边还有submodule的问题没有解决

我只是试试他们的issue。
